version: 2
updates:
  # Gradle dependencies for webapi
  - package-ecosystem: "gradle"
    directory: "/webapi"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
#  # npm dependencies for e2e tests
#  - package-ecosystem: "npm"
#    directory: "/test_work/e2e"
#    schedule:
#      interval: "weekly"
#    open-pull-requests-limit: 10
#    target-branch: "develop"
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "develop"